[workspace]
semver_check = true
allow_dirty = true # The "fixtures" is being marked as dirty.
changelog_config = "cliff.toml"
git_release_enable = false
git_tag_enable = false

[[package]]
name = "oxc_resolver"
version_group = "group"
changelog_include = ["oxc_resolver_napi"]
git_tag_enable = true
git_release_enable = true

[[package]]
name = "oxc_resolver_napi"
version_group = "group"
changelog_update = false
